module Fastbeans

  class RPCException < StandardError
    attr_accessor :orig_exc
  end

  class RemoteCallFailed < Fastbeans::RPCException; end
  class RemoteException < Fastbeans::RPCException; end
  class RemoteConnectionFailed  < Fastbeans::RPCException; end
  class RemoteConnectionDead  < Fastbeans::RPCException; end
  class AutogeneratedException < Fastbeans::RPCException; end
  class ResponseSignatureMismatch < RemoteConnectionFailed; end
  class ResponseReadTimeout < RemoteCallFailed; end

end
